/* Candidate26 synthetic authority. New namespace only; no production migration. */
(()=>{'use strict';
const NAME='mhpss-production-5ws-v2-outbox-v1',KEY='owned-5ws',SCHEMA='mhpss-5ws-session/0.4.0-approved-joint-review';
const ready=new Promise((res,rej)=>{const r=indexedDB.open(NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore('authority');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});
ready.catch(()=>{});
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel(NAME):null;if(channel)channel.onmessage=()=>window.dispatchEvent(new Event('authority26change'));
const memory=[];const empty=()=>({version:1,generation:0,envelopes:[],sources:{},recoveries:[]});
function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';}
async function hash(text){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
function sid(token){return token.replace(/-r[1-9][0-9]*(?:-a[a-f0-9]{12})?$/,'');}
function receipt(item,ack){const pre=JSON.parse(item.body).predecessor,expected=pre===null?1:(pre&&Number.isSafeInteger(pre.revision)&&pre.revision>=1?pre.revision+1:NaN);if(!ack||typeof ack!=='object'||Array.isArray(ack)||Object.keys(ack).sort().join(',')!=='event_id,request_sha256,revision,status'||ack.status!=='accepted'||ack.request_sha256!==item.sha256||!Number.isSafeInteger(ack.revision)||ack.revision!==expected||typeof ack.event_id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(ack.event_id)||(pre&&ack.event_id===pre.event_id))throw Error('Exact request acknowledgement missing or malformed');}
async function raw(){const db=await ready;return new Promise((res,rej)=>{const tx=db.transaction('authority'),r=tx.objectStore('authority').get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function validate(text){if(text!==undefined&&(typeof text!=='string'||text.length>2097152))throw Error('Bounded raw authority HOLD');const s=text===undefined?empty():JSON.parse(text);if(!s||typeof s!=='object'||Array.isArray(s)||Object.keys(s).sort().join(',')!=='envelopes,generation,recoveries,sources,version'||s.version!==1||!Number.isSafeInteger(s.generation)||s.generation<0||!Array.isArray(s.envelopes)||!Array.isArray(s.recoveries)||!s.sources||typeof s.sources!=='object'||Array.isArray(s.sources)||s.envelopes.length+s.recoveries.length>512)throw Error('Corrupt or bounded authority; recovery HOLD');const tokens=new Set();
for(const x of [...s.envelopes,...s.recoveries]){if(!x||typeof x!=='object'||Array.isArray(x)||typeof x.body!=='string'||x.body.length>131072||typeof x.token!=='string'||!/^report-[a-z0-9-]{1,80}$/.test(x.token)||x.session!==sid(x.token)||typeof x.sha256!=='string'||!/^[a-f0-9]{64}$/.test(x.sha256)||await hash(x.body)!==x.sha256)throw Error('Immutable body digest/metadata mismatch; recovery HOLD');const req=JSON.parse(x.body);if(canonical(req)!==x.body||Object.keys(req).sort().join(',')!=='payload,predecessor')throw Error('Malformed immutable body; recovery HOLD');const recovery=s.recoveries.includes(x),keys=Object.keys(x).sort().join(',');if(!['durably_queued','remotely_acknowledged'].includes(x.state))throw Error('Malformed envelope/recovery state');if(keys!==(x.state==='remotely_acknowledged'?(recovery?'ack,body,reason,session,sha256,state,token':'ack,body,session,sha256,state,token'):(recovery?'body,reason,session,sha256,state,token':'body,session,sha256,state,token')))throw Error('Unexpected immutable envelope/recovery metadata');if(recovery){if(typeof x.reason!=='string'||x.reason.length>1024||!x.reason.trim()||/[\u0000-\u001f\u007f]/.test(x.reason))throw Error('Malformed recovery reason');}else{if(tokens.has(x.token))throw Error('Duplicate envelope token');tokens.add(x.token);}if(x.state==='remotely_acknowledged')receipt(x,x.ack);}
if(s.generation<s.envelopes.length+s.recoveries.length)throw Error('Source generation/obligation mismatch; recovery HOLD');const latest={};for(const x of s.envelopes)latest[x.session]=x;for(const [id,x] of Object.entries(latest)){const p=s.sources[id];if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).sort().join(',')!=='sha256,token'||p.token!==x.token||p.sha256!==x.sha256)throw Error('Source selector mismatch; recovery HOLD');}if(Object.keys(s.sources).length!==Object.keys(latest).length)throw Error('Orphan source selector; recovery HOLD');return s;}
async function snapshot(){return validate(await raw());}
async function hook(phase){if(typeof window.__AUTHORITY26_TEST_HOOK==='function')await window.__AUTHORITY26_TEST_HOOK(phase);}
async function commit(before,state,kind){if(state.generation>=Number.MAX_SAFE_INTEGER)throw Error('Authority generation exhausted');state.generation++;const text=canonical(state);if(text.length>2097152)throw Error('Bounded authority full; export required');await validate(text);await hook(kind+':before-commit');const db=await ready;await new Promise((res,rej)=>{const tx=db.transaction('authority','readwrite',{durability:'strict'}),st=tx.objectStore('authority'),r=st.get(KEY);let error;r.onsuccess=()=>{if(r.result!==before){error=Error('Generation changed before commit');tx.abort();return;}if(window.__AUTHORITY26_TEST_ABORT===kind){error=Error('Injected transaction abort (not real quota exhaustion)');tx.abort();return;}st.put(text,KEY);};tx.oncomplete=res;tx.onabort=()=>rej(error||tx.error||Error('Durable authority write failed'));tx.onerror=()=>{};});window.dispatchEvent(new Event('authority26change'));if(channel)channel.postMessage('committed');await hook(kind+':after-commit');return state;}
async function mutate(fn,kind){for(let i=0;i<8;i++){const before=await raw(),s=await validate(before);const out=fn(s);try{await commit(before,s,kind);return out;}catch(e){if(!String(e).includes('Generation changed'))throw e;}}throw Error('Authority contention; retry required');}
async function enqueue(token,payload,predecessor=null,options={}){const body=canonical({payload,predecessor}),sha256=await hash(body),item={token,session:sid(token),body,sha256,state:'durably_queued'};if(!/^report-[a-z0-9-]{1,80}$/.test(token))throw Error('Typed report identity required');
try{const before=await raw(),s=await validate(before),expected=options.expectedGeneration??s.generation;if(!Number.isSafeInteger(expected)||expected<0)throw Error('Safe expected generation required');const prior=s.envelopes.find(x=>x.token===token);if(prior&&prior.body===body)return prior;if(prior||expected!==s.generation){await mutate(q=>{q.recoveries.push({...item,reason:'source-generation-conflict'});},'conflict');throw Error('Source conflict; attempted body durably recoverable; not saved or queued');}s.envelopes.push(item);s.sources[item.session]={token,sha256};await commit(before,s,'save');return item;}catch(e){if(String(e).includes('Generation changed')){try{await mutate(q=>{q.recoveries.push({...item,reason:'source-generation-conflict'});},'conflict');}catch(_){memory.push({...item,reason:'conflict recovery not durable'});}}else if(!String(e).includes('durably recoverable'))memory.push({...item,reason:String(e)});throw e;}}
async function all(){return (await snapshot()).envelopes;}
async function pending(){return (await all()).filter(x=>x.state==='durably_queued');}
async function acknowledge(item,ack){if(await hash(item.body)!==item.sha256)throw Error('Immutable body digest mismatch');receipt(item,ack);await hook('ack:received');await mutate(s=>{const x=s.envelopes.find(x=>x.token===item.token);if(!x||x.body!==item.body||x.sha256!==item.sha256)throw Error('Exact pending request changed');if(x.state==='remotely_acknowledged'&&canonical(x.ack)!==canonical(ack))throw Error('Immutable receipt changed');x.state='remotely_acknowledged';x.ack=ack;},'ack');}
async function conflict(item){await mutate(s=>{const x=s.envelopes.find(x=>x.token===item.token);if(x&&x.state==='durably_queued'&&!s.recoveries.some(r=>r.token===x.token&&r.sha256===x.sha256)){s.recoveries.push({...x,reason:'transport-refusal; deliberate refresh/rebase required'});}},'conflict');}
let inFlight=null;
function flush(send){if(inFlight)return inFlight;inFlight=(async()=>{let error=null;try{for(const item of await pending()){try{const req=JSON.parse(item.body);if(req.payload?.schema!==SCHEMA)throw Error('Historical schema HOLD; never dispatched');await hook('dispatch:before');await acknowledge(item,await send(item.token,req,item.sha256));}catch(e){error=String(e);if(error.includes('HTTP 403'))await conflict(item);}}}catch(e){return {state:'recovery_hold',pending:null,error:String(e)};}return {...await status(),...(error?{error}:{})};})().finally(()=>inFlight=null);return inFlight;}
async function status(){try{const s=await snapshot(),pending=s.envelopes.filter(x=>x.state==='durably_queued').length;return {state:memory.length?'memory_only_recovery':s.recoveries.length?'conflict_recovery_hold':pending?'durably_queued':'no_pending_requests',pending,recoveries:s.recoveries.length,unsaved:memory.length,generation:s.generation};}catch(e){return {state:'recovery_hold',pending:null,error:String(e)};}}
async function clearOwned(scope,expectedGeneration){if(typeof scope!=='string'||!/^report-[a-z0-9-]{1,80}$/.test(scope)||!Number.isSafeInteger(expectedGeneration))throw Error('Explicit owned scope and safe generation required');const before=await raw(),s=await validate(before);if(s.generation!==expectedGeneration)throw Error('Clear generation conflict');if(memory.some(x=>x.session===scope)||s.recoveries.some(x=>x.session===scope)||s.envelopes.some(x=>x.session===scope&&x.state!=='remotely_acknowledged'))throw Error('Unresolved obligations refuse clear');s.envelopes=s.envelopes.filter(x=>x.session!==scope);delete s.sources[scope];await commit(before,s,'clear');}
async function historical(){return [];}
async function recoveryExport(){let current=[],authority=null,error=null,text=null,history=[];try{text=await raw();authority=await validate(text);current=authority.envelopes;}catch(e){error=String(e);}try{history=await historical();}catch(e){error=(error||'')+'; historical HOLD '+String(e);}return {classification:'RESTRICTED DEVICE RECOVERY; legacy HOLD; no production migration',current,authority,raw_authority:text??null,error,memory_only:memory.slice(),historical_read_only:history};}
window.SESSION_QUEUE=Object.freeze({enqueue,pending,flush,status,all,historical,recoveryExport,snapshot,acknowledge,clearOwned,namespace:NAME});
})();
