(function(){
'use strict';const $=id=>document.getElementById(id),C=window.CODES,S=window.STORE;let seq=0;
function safeText(el,text){el.textContent=text;}
function fill(el,list,preserve=false){const prior=el.value;el.replaceChildren();el.append(new Option('— choose —',''));list.filter(x=>!x.retired).forEach(x=>el.append(new Option(C.label(x),x.code||x.pcode)));if(preserve)el.value=prior;}
[['org','ORGS'],['cadre','CADRES'],['district','DISTRICTS'],['modality','MODALITIES'],['activity','ACTIVITIES'],['status','STATUS']].forEach(([id,list])=>fill($(id),C[list]));
fill($('province'),[{code:'',name:'All provinces'},...Array.from(new Set(C.DISTRICTS.map(x=>x.province).filter(Boolean))).map(x=>({code:x,name:x}))]);
// Explicit intents: user geography changes reset; language repaint retains valid state.
function geoState(){return {site:$('site').value,palika:$('palika').value,ward:$('ward').value,other:$('siteOther').value};}
function renderGeo(state){
 const district=$('district').value;
 fill($('site'),C.FORM_SITES.filter(x=>!district||x.district===district));
 $('site').append(new Option('Palika level — no specific site','PALIKA'),new Option('Other — specify','OTHER'));
 fill($('palika'),C.PALIKAS.filter(x=>!district||x.district===district));
 $('site').value=state.site;$('palika').value=state.palika;
 $('siteOther').value=$('site').value==='OTHER'?state.other:'';
 renderGeoVisibility();renderWard(state.ward);
}
function renderGeoVisibility(){const value=$('site').value;$('siteOtherWrap').hidden=value!=='OTHER';$('palikaWrap').hidden=!['PALIKA','OTHER'].includes(value);$('districtOtherWrap').hidden=$('district').value!=='OTH';}
function renderWard(prior){const site=C.siteByCode[$('site').value],palika=C.palikaByCode[site&&site.palika||$('palika').value];$('ward').replaceChildren(new Option('— whole palika / not known —',''));if(palika&&palika.wards)for(let i=1;i<=palika.wards;i++)$('ward').append(new Option('Ward '+i,String(i)));$('ward').closest('.f').hidden=!(palika&&palika.wards);$('ward').value=Array.from($('ward').options).some(x=>x.value===prior)?prior:'';}
function clearGeo(){renderGeo({site:'',palika:'',ward:'',other:''});}
function provinceChanged(){fill($('district'),C.DISTRICTS.filter(x=>!$('province').value||x.province===$('province').value));clearGeo();}
function districtChanged(){clearGeo();}
function siteChanged(){$('palika').value='';$('siteOther').value='';renderGeoVisibility();renderWard('');}
function palikaChanged(){renderWard('');}
function repaintGeo(){renderGeo(geoState());}
$('province').onchange=provinceChanged;$('district').onchange=districtChanged;$('site').onchange=siteChanged;$('palika').onchange=palikaChanged;
clearGeo();
C.TARGET_GROUPS.forEach(x=>{const l=document.createElement('label');l.className='chk';const i=document.createElement('input');i.type='checkbox';i.value=x.code;l.append(i,document.createTextNode(C.label(x)));$('tgs').append(l);});
$('tgs').onchange=()=>{$('tgOtherWrap').hidden=!$('tgs').querySelector('input[value="TG-OTH"]:checked');};
for(const [id,wrap,other]of [['org','orgOtherWrap','OTHER'],['cadre','cadreOtherWrap','OTH'],['modality','modalityOtherWrap','OTH']])if($(wrap))$(id).onchange=()=>{$(wrap).hidden=$(id).value!==other;};
$('activity').onchange=()=>{$('activityOtherWrap').hidden=!(C.activityByCode[$('activity').value]||{}).other;};
const banner=$('iuPreviewNotice');banner.replaceChildren();const strong=document.createElement('b');strong.textContent='REVIEW ONLY · synthetic data · no save, queue or network delivery';banner.append(strong);const note=document.createElement('p');note.textContent='Original live frontend retained. Multiple-activity/cadre additions are English pending approved Nepali. No production connection.';banner.append(note);$('iuSyncStatus').replaceChildren();$('iuSyncStatus').append(Object.assign(document.createElement('b'),{textContent:'Production disconnected'}),Object.assign(document.createElement('span'),{textContent:'Review runs in memory only. Nothing is saved or acknowledged remotely.'}));
const offline=document.querySelector('[data-iu-operational-copy="offline"]');offline.textContent='Isolated review: this page does not test offline persistence or delivery.';
for(const key of ['f4.lede','f4.actHelp'])document.querySelectorAll('[data-i18n="'+key+'"]').forEach(el=>{el.removeAttribute('data-i18n');el.textContent=key==='f4.lede'?'One review session, several activities. Session attendance is counted once; activity participation can overlap.':'First activity below; add further activities from the same session.';});
// Add, rather than replace, existing controls and layout.
function container(id,after,title){const e=document.createElement('div');e.id=id;e.className='review-added';const h=document.createElement('h3');h.textContent=title;e.append(h);after.after(e);return e;}
const act=container('extraActivities',$('activityOtherWrap'),'Additional activities in the same session — English review');
const firstLabel=document.createElement('label');firstLabel.textContent='Participants in first activity';const firstCount=document.createElement('input');firstCount.id='firstActivityCount';firstCount.type='number';firstCount.min='0';firstCount.step='1';firstLabel.append(firstCount);act.append(firstLabel);
const rows=document.createElement('div');rows.id='activityRows';act.append(rows);const add=document.createElement('button');add.id='addActivity';add.type='button';add.className='btn sec';add.textContent='Add activity';act.append(add);
const staff=container('extraCadres',$('cadreOtherWrap').parentElement,'Numbers by cadre — English review');const firstStaff=document.createElement('label');firstStaff.textContent='Number of staff in first selected cadre';const n=document.createElement('input');n.id='firstCadreCount';n.type='number';n.min='0';n.step='1';firstStaff.append(n);staff.append(firstStaff);const staffRows=document.createElement('div');staffRows.id='cadreRows';staff.append(staffRows);const addStaff=document.createElement('button');addStaff.type='button';addStaff.id='addCadre';addStaff.className='btn sec';addStaff.textContent='Add cadre';staff.append(addStaff);
function appendRow(parent,list,kind,code='',value=''){const row=document.createElement('div');row.className='review-row';row.dataset.kind=kind;const label=document.createElement('label');label.textContent=kind==='activity'?'Activity':'Cadre';const select=document.createElement('select');select.setAttribute('aria-label',label.textContent+' '+(++seq));fill(select,list);select.value=code;label.append(select);const countLabel=document.createElement('label');countLabel.textContent=kind==='activity'?'Participants':'Staff';const count=document.createElement('input');count.type='number';count.min='0';count.step='1';count.value=value;count.setAttribute('aria-label',countLabel.textContent+' '+seq);countLabel.append(count);const remove=document.createElement('button');remove.type='button';remove.className='btn grey';remove.textContent='Remove';remove.onclick=()=>{row.remove();invalidate();};row.append(label,countLabel,remove);rowOther(row,kind);if(kind==='activity')activityDetail(row);parent.append(row);}
function activityDetail(parent){const d=document.createElement('details');d.className='activity-detail';const summary=document.createElement('summary');summary.textContent='Age and sex counts for this activity — optional';d.append(summary);const hint=document.createElement('p');hint.textContent='Leave every cell blank if not recorded. If recorded, enter all cells including explicit zero. Counts describe this activity, not a new session. Legacy bands are retained; 10–19 cannot be split into under/over 18.';d.append(hint);const table=document.createElement('table');table.className='counts';const cap=document.createElement('caption');cap.textContent='Activity attendance by current live age bands and recorded sex';table.append(cap);const head=document.createElement('thead'),tr=document.createElement('tr');for(const title of ['Age','Female','Male','Not recorded']){const th=document.createElement('th');th.scope='col';th.textContent=title;tr.append(th);}head.append(tr);table.append(head);const body=document.createElement('tbody');for(const b of S.BANDS){const row=document.createElement('tr'),th=document.createElement('th');th.scope='row';th.textContent=b.label;row.append(th);for(const [id,label]of [[b.f,'Female'],[b.m,'Male'],[b.o,'Not recorded']]){const td=document.createElement('td'),input=document.createElement('input');input.type='number';input.min='0';input.step='1';input.dataset.cell=id;input.setAttribute('aria-label',label+', '+b.label+', this activity');td.append(input);row.append(td);}body.append(row);}table.append(body);d.append(table);for(const [fill,text] of [['zero','Fill blank cells with explicit zero'],['clear','Clear counts — not recorded']]){const button=document.createElement('button');button.type='button';button.className='btn sec';button.dataset.fill=fill;button.textContent=text;button.onclick=()=>{d.querySelectorAll('[data-cell]').forEach(input=>{if(fill==='clear')input.value='';else if(input.value==='')input.value='0';});invalidate();};d.append(button);}parent.append(d);return d;}
function detailValues(d){const inputs=Array.from(d.querySelectorAll('[data-cell]'));return inputs.every(x=>x.value==='')?null:Object.fromEntries(inputs.map(x=>[x.dataset.cell,countValue(x.value)]));}
function rowOther(row,kind){const el=document.createElement('label');el.className='row-other';el.textContent=kind==='activity'?'Other activity — describe programme only, no people':'Other cadre — role only, no names';const input=document.createElement('input');input.type='text';input.maxLength=160;input.dataset.other='true';el.append(input);row.append(el);const select=row.querySelector('select');function reveal(){el.hidden=kind==='activity'?!(C.activityByCode[select.value]||{}).other:select.value!=='OTH';}select.addEventListener('change',()=>{input.value='';reveal();});reveal();}
const firstDetail=activityDetail(act);act.insertBefore(firstDetail,rows);
add.onclick=()=>{appendRow(rows,C.ACTIVITIES,'activity');invalidate();};addStaff.onclick=()=>{appendRow(staffRows,C.CADRES,'cadre');invalidate();};
// Preserve the full legacy fields in a device/source section; not a server-ready body.
function legacy(){let r={};document.querySelectorAll('#f input[id],#f select[id],#f textarea[id]').forEach(el=>{if(!['firstActivityCount','firstCadreCount'].includes(el.id))r[el.id]=el.value;});r.targetGroups=Array.from($('tgs').querySelectorAll('input:checked')).map(x=>x.value);r.partners=$('partners').value.split(',').map(x=>x.trim()).filter(Boolean);r.countBasis='CONTACTS';r.distinctPeople='';return r;}
function countValue(v){return v===''?null:Number(v);}
function make(){const l=legacy();const activities=[{code:l.activity,attendance:countValue(firstCount.value),disaggregation:detailValues(firstDetail)}],cadres=l.cadre?[{code:l.cadre,count:countValue(n.value)}]:[];
if((C.activityByCode[l.activity]||{}).other)activities[0].other=l.activityOther;
if(l.cadre==='OTH')cadres[0].other=l.cadreOther;
rows.querySelectorAll('.review-row').forEach(e=>{const a={code:e.querySelector('select').value,attendance:countValue(e.querySelector('input').value),disaggregation:detailValues(e.querySelector('.activity-detail'))};if((C.activityByCode[a.code]||{}).other)a.other=e.querySelector('[data-other]').value;activities.push(a);});
staffRows.querySelectorAll('.review-row').forEach(e=>{const c={code:e.querySelector('select').value,count:countValue(e.querySelector('input').value)};if(c.code==='OTH')c.other=e.querySelector('[data-other]').value;cadres.push(c);});
return {schema:'mhpss-5ws-session/0.3.0-review',ageBandVersion:'legacy-20260921',attendance:countValue(l.reachedTotal),activities,cadres,deviceOnly:l};}
function wire(){const r=make(),l=r.deviceOnly;const sessionCells=Object.fromEntries(S.PART_IDS.map(id=>[id,countValue(l[id])]));const body={dateBS:l.dateBS,description:l.description,sessionDisaggregation:Object.values(sessionCells).every(x=>x===null)?null:sessionCells,ofWhom:Object.fromEntries(S.OF_WHOM.map(id=>[id,countValue(l[id])])),schema:r.schema,ageBandVersion:r.ageBandVersion,org:l.org,dateAD:l.dateAD,sessionTime:l.sessionTime,district:l.district,palika:l.palika,site:l.site,ward:l.ward,attendance:r.attendance,activities:r.activities,cadres:r.cadres,partners:l.partners,targetGroups:l.targetGroups,modality:l.modality,status:l.status,disability:{asked:l.disAsked,counts:Object.fromEntries(S.DISABILITY.map(id=>[id,countValue(l[id])]))}};const site=C.siteByCode[l.site];if(site&&site.palika)body.palika=site.palika;for(const [field,chosen]of [['orgOther',l.org==='OTHER'],['modalityOther',l.modality==='OTH'],['siteOther',l.site==='OTHER'],['districtOther',l.district==='OTH'],['targetGroupsOther',l.targetGroups.includes('TG-OTH')]])if(chosen)body[field]=l[field==='targetGroupsOther'?'targetGroupOther':field];return body;}

function check(r){let e=S.validate(r.deviceOnly);if(window.HOSTED_REOPEN)e=e.filter(x=>!['Focal point name is required','Focal point phone is required'].includes(x));for(const input of document.querySelectorAll('#f input[type=number]'))if(input.validity.badInput)e.push('Enter a valid whole number: '+(input.getAttribute('aria-label')||input.id||'count'));if(!Number.isInteger(r.attendance)||r.attendance<0)e.push('Session attendance must be a nonnegative integer');for(const id of [...S.PART_IDS,...S.OF_WHOM,...S.DISABILITY]){const raw=r.deviceOnly[id];if(raw!==''&&raw!==undefined&&(!Number.isInteger(Number(raw))||Number(raw)<0))e.push('Invalid integer count: '+id);}const sessionValues=S.PART_IDS.map(id=>countValue(r.deviceOnly[id]));if(sessionValues.some(x=>x!==null)&&sessionValues.some(x=>x===null))e.push('Complete the session matrix including explicit zeros, or leave every cell blank');if(sessionValues.every(x=>x!==null)&&sessionValues.reduce((n,v)=>n+v,0)!==r.attendance)e.push('Recorded session matrix must equal session attendance, including zero');const ds=S.DISABILITY.map(id=>countValue(r.deviceOnly[id]));if(ds.filter(x=>x!==null).reduce((n,v)=>n+v,0)>r.attendance)e.push('Recorded disability cells cannot sum above session attendance');if(firstCount.value==='')e.push('First activity attendance required');for(const a of r.activities){if(!C.activityByCode[a.code])e.push('Select a valid activity');if((C.activityByCode[a.code]||{}).other&&(!a.other||!a.other.trim()))e.push('Describe Other activity without identifying people');if(a.disaggregation!==null){const vals=Object.values(a.disaggregation);if(vals.some(v=>!Number.isInteger(v)||v<0))e.push('Complete every activity age/sex cell with a nonnegative integer, or leave all blank');else if(vals.reduce((n,v)=>n+v,0)!==a.attendance)e.push('Activity age/sex counts must equal that activity attendance');}if(!Number.isInteger(a.attendance)||a.attendance<0||a.attendance>r.attendance)e.push('Activity attendance must be an integer within session attendance');}if(new Set(r.activities.map(x=>x.code)).size!==r.activities.length)e.push('Duplicate activity code');for(const a of r.cadres)if(!C.CADRES.some(x=>x.code===a.code&&!x.retired)||!Number.isInteger(a.count)||a.count<0)e.push('Cadre and integer staff count required');for(const c of r.cadres)if(c.code==='OTH'&&(!c.other||!c.other.trim()))e.push('Specify Other cadre role, not a name');if(new Set(r.cadres.map(x=>x.code)).size!==r.cadres.length)e.push('Duplicate cadre');return [...new Set(e)];}
const result=document.createElement('section');result.id='reviewProjection';result.className='card';result.hidden=true;$('f').after(result);function invalidate(){result.hidden=true;window.REVIEW_RESULT=null;}
function counters(){const r=legacy(),any=S.PART_IDS.some(id=>$(id).value!=='');let female=0,male=0,unknown=0;for(const band of S.BANDS){const vals=[band.f,band.m,band.o].map(id=>countValue($(id).value));const sum=vals.reduce((n,v)=>n+(Number.isFinite(v)&&v>=0?v:0),0);$('r'+band.key).textContent=vals.some(v=>v!==null)?sum:'—';female+=Number(r[band.f])||0;male+=Number(r[band.m])||0;unknown+=Number(r[band.o])||0;}for(const [id,n] of [['cF',female],['cM',male],['cO',unknown],['cAll',female+male+unknown]])$(id).textContent=any?n:'—';$('tallyVal').textContent=any?female+male+unknown:'—';let lower=0,upper=0;for(const b of S.BANDS){const v=(Number(r[b.f])||0)+(Number(r[b.m])||0)+(Number(r[b.o])||0);if(b.child)lower+=v;else upper+=v;}$('rollU18').textContent=any?lower:'—';$('roll18').textContent=any?upper:'—';$('descCount').textContent=$('description').value.length;}
$('f').addEventListener('input',()=>{invalidate();counters();});$('f').addEventListener('change',invalidate);

$('f').onsubmit=e=>{e.preventDefault();invalidate();const r=make(),errors=check(r);$('problems').textContent=errors.join('; ');result.hidden=errors.length>0;if(errors.length){$('problems').focus();return;}const p=window.SESSION_READER.project(r);result.replaceChildren();const h=document.createElement('h2');h.textContent='Layer 2 synthetic read-back — not remote delivery';const summary=document.createElement('p');summary.id='reviewTotals';summary.textContent=`Sessions ${p.sessions} · session attendance ${p.sessionAttendance} · activity participations ${p.activityParticipations} · staff-sessions ${p.staffSessions} · period-unique people unknown`;result.append(h,summary);const warn=document.createElement('p');warn.textContent='No record is saved. Source/device fields including focal contacts are not a hosted payload. Trusted validator, transport stripping, backend acknowledgement and operational Hub integration remain release gates. Activity matrices use legacy age bands; unknown sex is not an Other-gender category.';result.append(warn);window.REVIEW_RESULT={summary:p,record:r};};
const button=document.querySelector('button[type="submit"][form="f"]');button.removeAttribute('data-i18n');button.textContent='Review report — no save';document.querySelector('[data-iu-operational-copy="save"]').textContent='Review-only: no local record, queue, remote acknowledgement or publication. Use synthetic values.';
const saved=document.querySelector('section.saved');saved.hidden=true;['reset','expCsv','expJson','wipe'].forEach(id=>{$(id).disabled=true;});document.querySelectorAll('.top a').forEach(a=>a.removeAttribute('href'));
const ex=document.createElement('button');ex.type='button';ex.id='syntheticExample';ex.className='btn sec';ex.textContent='Load synthetic example';$('s1').append(ex);
const reviewButton=document.createElement('button');reviewButton.type='submit';reviewButton.className='btn';reviewButton.textContent='Review report — no save';reviewButton.id='reviewButton';reviewButton.setAttribute('form','f');$('s5').append(reviewButton);ex.setAttribute('form','f');$('addActivity').setAttribute('form','f');$('addCadre').setAttribute('form','f');$('f').noValidate=true;
document.querySelector('.iu-start').onclick=()=>document.body.classList.add('iu-entry-active');
ex.onclick=()=>{$('org').value='TPO';$('focalName').value='SYNTHETIC REVIEW';$('focalPhone').value='9800000000';$('district').value='NUW';districtChanged();$('site').value='PALIKA';$('palika').value='NP0328301';renderGeoVisibility();renderWard('');$('dateAD').value='2026-10-06';$('sessionTime').value='10:00';$('activity').value='2.1';$('cadre').value='PSC';$('modality').value='COM';$('status').value='CMP';$('reachedTotal').value='30';firstCount.value='14';n.value='2';$('tgs').querySelector('input[value="TG-COM"]').checked=true;firstDetail.querySelectorAll('[data-cell]').forEach(x=>x.value='');rows.replaceChildren();staffRows.replaceChildren();appendRow(rows,C.ACTIVITIES,'activity','3.1',20);appendRow(staffRows,C.CADRES,'cadre','VOL',3);invalidate();counters();};
function reviewCopy(){for(const [key,text]of [['f4.step5','Review'],['f4.h1hint','Review input only'],['f4.h5check','Check the review report']])document.querySelectorAll('[data-i18n="'+key+'"]').forEach(el=>{el.removeAttribute('data-i18n');el.textContent=text;});document.querySelector('.ribbon').textContent='REVIEW ONLY — report data stays in memory; UI language preference may be remembered on this device.';}
reviewCopy();counters();
document.addEventListener('i18n:changed',()=>{invalidate();[['org','ORGS'],['cadre','CADRES'],['modality','MODALITIES'],['activity','ACTIVITIES'],['status','STATUS']].forEach(([id,list])=>fill($(id),C[list],true));fill($('district'),C.DISTRICTS.filter(x=>!$('province').value||x.province===$('province').value),true);repaintGeo();for(const e of document.querySelectorAll('.review-row'))fill(e.querySelector('select'),e.dataset.kind==='activity'?C.ACTIVITIES:C.CADRES,true);for(const e of $('tgs').querySelectorAll('label')){const code=e.querySelector('input').value;const item=C.TARGET_GROUPS.find(x=>x.code===code);const input=e.querySelector('input');e.replaceChildren(input,document.createTextNode(C.label(item)));}reviewCopy();counters();});

function prefill(payload){
 const p=structuredClone(payload);$('f').reset();rows.replaceChildren();staffRows.replaceChildren();
 const set=(id,v)=>{$(id).value=v===null||v===undefined?'':String(v);};
 for(const id of ['org','orgOther','dateAD','dateBS','sessionTime','description','district','districtOther','modality','modalityOther','status','siteOther'])set(id,p[id]);
 set('province',(C.DISTRICTS.find(x=>x.code===p.district)||{}).province||'');
 fill($('district'),C.DISTRICTS.filter(x=>!$('province').value||x.province===$('province').value));set('district',p.district);
 renderGeo({site:p.site,palika:p.palika,ward:p.ward,other:p.siteOther||''});
 set('reachedTotal',p.attendance);set('partners',p.partners.join(', '));set('targetGroupOther',p.targetGroupsOther);
 for(const input of $('tgs').querySelectorAll('input'))input.checked=p.targetGroups.includes(input.value);
 $('tgOtherWrap').hidden=!p.targetGroups.includes('TG-OTH');
 for(const id of S.PART_IDS)set(id,p.sessionDisaggregation?.[id]);
 for(const id of S.OF_WHOM)set(id,p.ofWhom[id]);
 set('disAsked',p.disability.asked);for(const id of S.DISABILITY)set(id,p.disability.counts[id]);
 const a=p.activities[0],c=p.cadres[0];set('activity',a.code);set('activityOther',a.other);set('firstActivityCount',a.attendance);
 set('cadre',c?.code);set('cadreOther',c?.other);set('firstCadreCount',c?.count);
 const matrix=(el,m)=>el.querySelectorAll('[data-cell]').forEach(x=>{x.value=m?.[x.dataset.cell]===null||m?.[x.dataset.cell]===undefined?'':String(m[x.dataset.cell]);});
 matrix(firstDetail,a.disaggregation);
 for(const v of p.activities.slice(1)){appendRow(rows,C.ACTIVITIES,'activity',v.code,v.attendance??'');const row=rows.lastElementChild;row.querySelector('[data-other]').value=v.other||'';matrix(row,v.disaggregation);}
 for(const v of p.cadres.slice(1)){appendRow(staffRows,C.CADRES,'cadre',v.code,v.count??'');staffRows.lastElementChild.querySelector('[data-other]').value=v.other||'';}
 for(const [id,wrap,other] of [['org','orgOtherWrap','OTHER'],['cadre','cadreOtherWrap','OTH'],['modality','modalityOtherWrap','OTH']])$(wrap).hidden=$(id).value!==other;
 $('activityOtherWrap').hidden=!(C.activityByCode[a.code]||{}).other;
 // Hosted payload never contains professional focal contacts or person identity.
 for(const id of ['focalName','focalPhone','focalEmail'])set(id,'');
 window.HOSTED_REOPEN=true;document.body.classList.add('iu-entry-active');invalidate();counters();
 if(canonicalWire(wire())!==canonicalWire(p))throw Error('Full hosted payload prefill mismatch; do not queue');
}
function canonicalWire(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canonicalWire).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonicalWire(v[k])).join(',')+'}';}
window.INTEGRATION_REVIEW={make,check,wire,prefill};
})();
