/* Presentation-only review entry. Existing native form/queue/transport retained. */
(()=>{'use strict';
const $=id=>document.getElementById(id),panels=['formPanel','reportsPanel','loginPanel'];
function show(id){for(const p of panels)$(p).hidden=p!==id;$(id).scrollIntoView({block:'start',behavior:'instant'});}
async function repaint(){const s=await SESSION_QUEUE.status();$('queueSummary').textContent=s.state==='memory_only_recovery'?'NOT SAVED — memory-only recovery; export before closing.':s.state==='recovery_hold'?'Recovery HOLD — authority cannot be read; no delivery claim.':s.state==='conflict_recovery_hold'?'Conflict recovery HOLD — retained attempts require deliberate recovery.':s.pending?'Saved on this review device and queued: '+s.pending+'. Not remotely acknowledged.':'No pending requests in this review queue. This does not prove server receipt.';$('technicalState').textContent=JSON.stringify({operationalDispatch:ENDPOINT_CONFIG.activationEnabled,device:s,namespace:SESSION_QUEUE.namespace},null,2);}
async function reports(){show('reportsPanel');$('myReports').replaceChildren();try{const items=await SESSION_QUEUE.all();for(const item of items){const request=JSON.parse(item.body),p=request.payload,li=document.createElement('li'),d=document.createElement('details'),summary=document.createElement('summary');summary.textContent=p.dateAD+' · '+p.org+' · '+(item.state==='durably_queued'?'queued, not received':'exact synthetic receipt recorded');d.append(summary);const text=document.createElement('p');text.textContent='Session attendance '+p.attendance+'; activity participations '+p.activities.reduce((n,a)=>n+a.attendance,0)+'. Read-only device request; no hosted current-read or correction authority.';d.append(text);li.append(d);$('myReports').append(li);}$('localReportsState').textContent=items.length?items.length+' synthetic device request(s). No cloud confirmation.':'No synthetic device requests. No confirmed cloud reports.';}catch(_){$('localReportsState').textContent='Device authority unavailable. Export recovery; no empty/received claim.';}}
$('newReport').onclick=()=>{show('formPanel');$('form').contentWindow.document.querySelector('.iu-start')?.focus();};
$('showReports').onclick=reports;$('showLogin').onclick=()=>show('loginPanel');$('showSync').onclick=()=>{$('syncPanel').scrollIntoView({behavior:'instant'});repaint();};
$('refresh').textContent='Refresh this review device list';$('refresh').onclick=reports;
$('flush').textContent='Check pending status — delivery held';$('flush').onclick=repaint;
// Child cannot operate real Auth accounts; parent integrates existing email flow after review.
for(const id of ['sendLink','finishLink']){$(id).addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();$('loginStatus').textContent='Sign-in is held in this isolated review. No email sent, code consumed or account changed.';},true);}
const original=REVIEW_BRIDGE.submit;window.REVIEW_BRIDGE=Object.freeze({...REVIEW_BRIDGE,submit:async payload=>{const result=await original(payload);await repaint();return result;}});
window.addEventListener('authority26change',repaint);repaint();
})();
